version: '3.7'

networks:
  zon-kills:
    external: false

services:
  papera:
    image: itzg/minecraft-server:java17-alpine
    networks:
      - zon-kills
    volumes:
      - ./localDependencies:/data/plugins
    environment:
      - TYPE=PAPER
      - VERSION=1.19.2
      - EULA=TRUE
      - ONLINE_MODE=TRUE
      - OPS=erudosan0524
    stdin_open: true
    ports:
      - "25565:25565"
    tty: true
    restart: unless-stopped
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root