version: '3.7'

services:
  papera:
    image: itzg/minecraft-server:java17-alpine
    volumes:
      - ./localDependencies:/data/plugins
    environment:
      - TYPE=PAPER
      - VERSION=1.19.2
      - EULA=TRUE
      - ONLINE_MODE=TRUE
      - OPS=erudosan0524
    stdin_open: true
    ports:
      - "25565:25565"
    tty: true
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mc_db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MARIADB_DATABASE: zonkills
      MARIADB_ROOT_PASSWORD: root