version: '3.7'

services:
  papera:
    build:
        context: ./docker/paper
        dockerfile: Dockerfile
    environment:
      - TYPE=PAPER
      - VERSION=1.19.2
      - EULA=TRUE
      - ONLINE_MODE=TRUE
      - OPS=erudosan0524
    stdin_open: true
    networks:
      - default
    ports:
      - "25565:25565"
    tty: true
    restart: unless-stopped
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: mc_db
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    restart: always
    networks:
      - default
    environment:
      MARIADB_DATABASE: zonkills
      MARIADB_ROOT_PASSWORD: root